language: python
python:
  - 3.6

# command to install dependencies
install:
  - pip install -e .
  - pip install -r requirements.txt

before_script:
  - flake8

# command to run tests
script:
  - py.test --cov mplstyle --cov-report term-missing

after_success:
  - coveralls
